# Generated by Django 4.1.5 on 2023-01-27 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RegisterUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Emp_id', models.CharField(max_length=50)),
                ('FullName', models.CharField(max_length=100)),
                ('Designation', models.CharField(max_length=50)),
                ('Org', models.CharField(max_length=50)),
                ('Password', models.CharField(max_length=50)),
                ('ContactNumber', models.CharField(max_length=10)),
                ('Department', models.CharField(max_length=50)),
            ],
        ),
    ]
