# Generated by Django 4.1.5 on 2023-01-27 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendence', '0002_registeruser_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registeruser',
            name='Emp_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
